### ISSUE TITLE
How do you visualize the point cloud in the paper?

### ISSUE THREAD

**Issue by TiankaiHang** [alexzhou907/PVD#3]
Hi,

Thanks for your nice work!
May I ask how do you visualize the point cloud in the paper?

Best

**Comment by Ayanami2019** [comment]
Hello, do you know how to visualize point clouds as in the paper? I would appreciate it if you could tell me

**Comment by TiankaiHang** [comment]
@Ayanami2019 Use the tool mitsuba2.

**Comment by Ayanami2019** [comment]
Thanks！
